services:
  nginx:
    image: nginx:1.24.0
    container_name: nginx
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/usr/share/nginx/html
  redis:
    image: redis:7.2.5
    container_name: redis
    network_mode: "host"
